security.signing-key=MaYzkSjmkzPC57L
security.security-realm=Spring Boot JWT Example Realm

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080

security.jwt.client-id=testjwtclientid
security.jwt.client-secret=XY7kmzoNzl100
security.jwt.scope-read=read
security.jwt.scope-write=write
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization=TRACE